// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-0ySO2HIUhKhKOMwJm8AFl3u-SdQ0y4',
    appId: '1:507058856404:web:cb7941ad6e9b729f983641',
    messagingSenderId: '507058856404',
    projectId: 'm-recipe2',
    authDomain: 'm-recipe2.firebaseapp.com',
    storageBucket: 'm-recipe2.appspot.com',
    measurementId: 'G-YG7GJH3WVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARjj5k2TIi8TcBPFpIKKKbfkpvBN8c2Fg',
    appId: '1:507058856404:android:0fd50e9a0975997d983641',
    messagingSenderId: '507058856404',
    projectId: 'm-recipe2',
    storageBucket: 'm-recipe2.appspot.com',
  );
}
